// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtRyE96oB4_eutdK-pYUpKOY4cVdvK11w',
    appId: '1:128196352432:web:a6910a9238b4aabf4ade75',
    messagingSenderId: '128196352432',
    projectId: 'mementofirebase-3cfad',
    authDomain: 'mementofirebase-3cfad.firebaseapp.com',
    databaseURL: 'https://mementofirebase-3cfad-default-rtdb.firebaseio.com',
    storageBucket: 'mementofirebase-3cfad.appspot.com',
    measurementId: 'G-L2H3RD48HG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqkUHaMJNz8IFqf7wT1xhONW8lh-fkrCo',
    appId: '1:128196352432:android:cea37c063c03e3e34ade75',
    messagingSenderId: '128196352432',
    projectId: 'mementofirebase-3cfad',
    databaseURL: 'https://mementofirebase-3cfad-default-rtdb.firebaseio.com',
    storageBucket: 'mementofirebase-3cfad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKsNflPUe5PRLD9Fg42e3jPQJG82Pz12w',
    appId: '1:128196352432:ios:9385aff04811224a4ade75',
    messagingSenderId: '128196352432',
    projectId: 'mementofirebase-3cfad',
    databaseURL: 'https://mementofirebase-3cfad-default-rtdb.firebaseio.com',
    storageBucket: 'mementofirebase-3cfad.appspot.com',
    iosBundleId: 'com.example.memento',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKsNflPUe5PRLD9Fg42e3jPQJG82Pz12w',
    appId: '1:128196352432:ios:a128e6cf25328c8e4ade75',
    messagingSenderId: '128196352432',
    projectId: 'mementofirebase-3cfad',
    databaseURL: 'https://mementofirebase-3cfad-default-rtdb.firebaseio.com',
    storageBucket: 'mementofirebase-3cfad.appspot.com',
    iosBundleId: 'com.example.memento.RunnerTests',
  );
}
